"""Add customer_name, summary, search_vector to Conversation

Revision ID: 1cc855a33807
Revises: 9a1da8b16ff3
Create Date: 2026-09-23 12:56:42.015753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cc855a33807'
down_revision: Union[str, Sequence[str], None] = '9a1da8b16ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_conversations_search_vector', 'conversations', ['search_vector'], unique=False, postgresql_using='gin')
    
    op.execute("""
    CREATE FUNCTION conversations_search_trigger() RETURNS trigger AS $$
    BEGIN
      NEW.search_vector :=
        to_tsvector('english', coalesce(NEW.customer_name, '') || ' ' ||
                               coalesce(NEW.customer_identifier, '') || ' ' ||
                               coalesce(NEW.summary, ''));
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER conversations_search_update
    BEFORE INSERT OR UPDATE ON conversations
    FOR EACH ROW EXECUTE FUNCTION conversations_search_trigger();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS conversations_search_update ON conversations;")
    op.execute("DROP FUNCTION IF EXISTS conversations_search_trigger();")
    
    op.drop_index('ix_conversations_search_vector', table_name='conversations', postgresql_using='gin')
    op.drop_column('conversations', 'search_vector')
    op.drop_column('conversations', 'summary')
    op.drop_column('conversations', 'customer_name')
    # ### end Alembic commands ###
