"""Add domain and is_primary to WorkspaceIntegration

Revision ID: 8f0173094c07
Revises: 5a7f53623ea6
Create Date: 2026-10-02 11:27:40.041205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0173094c07'
down_revision: Union[str, Sequence[str], None] = '5a7f53623ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_integrations', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('workspace_integrations', sa.Column('is_primary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_integrations', 'is_primary')
    op.drop_column('workspace_integrations', 'domain')
    # ### end Alembic commands ###
