"""Add status column to workspace_members

Revision ID: df5dcd741a2e
Revises: 283d6e9fdee8
Create Date: 2026-09-22 16:51:19.721576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df5dcd741a2e'
down_revision: Union[str, Sequence[str], None] = '283d6e9fdee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes', schema='checkpoints')
    op.drop_table('checkpoint_writes', schema='checkpoints')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints', schema='checkpoints')
    op.drop_table('checkpoints', schema='checkpoints')
    op.drop_index(op.f('documents_embedding_hnsw'), table_name='documents', schema='rag', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('documents_fts_idx'), table_name='documents', schema='rag', postgresql_using='gin')
    op.drop_index(op.f('documents_metadata_idx'), table_name='documents', schema='rag', postgresql_using='gin')
    op.drop_table('documents', schema='rag')
    op.drop_index(op.f('resolved_tickets_embedding_hnsw'), table_name='resolved_tickets', schema='rag', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('resolved_tickets_fts_idx'), table_name='resolved_tickets', schema='rag', postgresql_using='gin')
    op.drop_table('resolved_tickets', schema='rag')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs', schema='checkpoints')
    op.drop_table('checkpoint_blobs', schema='checkpoints')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', schema='memory_store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store', schema='memory_store', postgresql_ops={'prefix': 'text_pattern_ops'})
    op.drop_table('store', schema='memory_store')
    op.drop_table('store_migrations', schema='memory_store')
    op.drop_table('checkpoint_migrations', schema='checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey')),
    schema='checkpoints'
    )
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey')),
    schema='memory_store'
    )
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey')),
    schema='memory_store'
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, schema='memory_store', postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, schema='memory_store', postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey')),
    schema='checkpoints'
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False, schema='checkpoints')
    op.create_table('resolved_tickets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, ((summary || ' '::text) || resolution))", persisted=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resolved_tickets_pkey')),
    sa.UniqueConstraint('ticket_id', name=op.f('resolved_tickets_ticket_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='rag'
    )
    op.create_index(op.f('resolved_tickets_fts_idx'), 'resolved_tickets', ['fts'], unique=False, schema='rag', postgresql_using='gin')
    op.create_index(op.f('resolved_tickets_embedding_hnsw'), 'resolved_tickets', ['embedding'], unique=False, schema='rag', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey')),
    sa.UniqueConstraint('doc_id', name=op.f('documents_doc_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='rag'
    )
    op.create_index(op.f('documents_metadata_idx'), 'documents', ['metadata'], unique=False, schema='rag', postgresql_using='gin')
    op.create_index(op.f('documents_fts_idx'), 'documents', ['fts'], unique=False, schema='rag', postgresql_using='gin')
    op.create_index(op.f('documents_embedding_hnsw'), 'documents', ['embedding'], unique=False, schema='rag', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey')),
    schema='checkpoints'
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False, schema='checkpoints')
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey')),
    schema='checkpoints'
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False, schema='checkpoints')
    # ### end Alembic commands ###
