from typing import Protocol, Dict, Any, runtime_checkable

from support_system.mcp_servers.order_account_mcp.adapters.schemas import (
    OrderStatusResult,
    RefundResult,
    CancelResult,
    AddressUpdateResult,
    BillingResult,
    OrderHistoryResult,
    AccountDetailsResult
)
from support_system.mcp_servers.inventory_mcp.adapters.schemas import (
    StockLevelResult,
    ReserveStockResult,
    UpdateStockCountResult
)

@runtime_checkable
class OrderAccountAdapterProtocol(Protocol):
    def get_order_status(self, order_id: str) -> OrderStatusResult: ...
    def get_order_history(self, customer_id: str) -> OrderHistoryResult: ...
    def get_account_details(self, customer_id: str) -> AccountDetailsResult: ...
    def get_billing_details(self, customer_id: str) -> BillingResult: ...
    def issue_refund(self, order_id: str, amount: float, reason: str, idempotency_key: str) -> RefundResult: ...
    def cancel_order(self, order_id: str, reason: str, idempotency_key: str) -> CancelResult: ...
    def update_shipping_address(self, order_id: str, new_address: Dict[str, Any], idempotency_key: str) -> AddressUpdateResult: ...

@runtime_checkable
class InventoryAdapterProtocol(Protocol):
    def get_stock_level(self, sku: str) -> StockLevelResult: ...
    def reserve_stock(self, sku: str, quantity: int, idempotency_key: str) -> ReserveStockResult: ...
    def update_stock_count(self, sku: str, new_count: int, reason: str, idempotency_key: str) -> UpdateStockCountResult: ...
